//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POC_ImageGallery_Features
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arts
    {
        public long Id { get; set; }
        public string IllustratorName { get; set; }
        public Nullable<long> Country { get; set; }
        public string Address { get; set; }
        public string email { get; set; }
        public string Rep { get; set; }
        public string Website { get; set; }
        public long Price { get; set; }
        public string Timeliness { get; set; }
        public Nullable<System.DateTime> Availability { get; set; }
        public string Launguage { get; set; }
        public Nullable<int> AgeGroup { get; set; }
        public string Categories { get; set; }
        public string ProgramsWorkedOn { get; set; }
        public string ArtCommissioner { get; set; }
        public byte[] Image { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string Keywords { get; set; }
    }
}
