//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POC_ImageGallery_Features
{
    using System;
    using System.Collections.Generic;
    
    public partial class chapterSpecImage
    {
        public long Id { get; set; }
        public Nullable<long> chapterId { get; set; }
        public Nullable<long> specId { get; set; }
        public Nullable<long> imageId { get; set; }
    
        public virtual Chapters Chapters { get; set; }
        public virtual Photos Photos { get; set; }
        public virtual Spec Spec { get; set; }
    }
}
