//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POC_ImageGallery_Features
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LightboxEntities : DbContext
    {
        public LightboxEntities()
            : base("name=LightboxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Photos> Photos { get; set; }
        public virtual DbSet<Arts> Arts { get; set; }
        public virtual DbSet<Chapters> Chapters { get; set; }
        public virtual DbSet<chapterSpecImage> chapterSpecImage { get; set; }
        public virtual DbSet<Spec> Spec { get; set; }
    }
}
