//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POC_ImageGallery_Features
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Photos()
        {
            this.chapterSpecImage = new HashSet<chapterSpecImage>();
            this.Spec = new HashSet<Spec>();
        }
    
        public long Id { get; set; }
        public string Vendor { get; set; }
        public string Terms { get; set; }
        public string Description { get; set; }
        public string CreditLine { get; set; }
        public string Restrictions { get; set; }
        public string Keywords { get; set; }
        public string ImageUrl { get; set; }
        public string AssetType { get; set; }
        public Nullable<System.DateTime> PropertyRelease { get; set; }
        public Nullable<long> Country { get; set; }
        public string Photoresearcher { get; set; }
        public byte[] Image { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsApproved { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chapterSpecImage> chapterSpecImage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spec> Spec { get; set; }
    }
}
